# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: i-o-e->w-o-r-k-s-!

description: > # this means to ignore newlines until "baseurl:"
  My personal site for blogging some technical writing.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://www.ioeworks.com" # the base hostname & protocol for your site

# Twitter user id - leave it empty for privacy
twitter: 

# Github user id - leave it empty for privacy
github: 

# LinkedIn user id - leave it empty for privacy
linkedin: 

# Just give it any value or leave it empty
rss: true

# Shortcuts site
shortcuts: http://i.ioeworks.com

# Contact email
email: yuanjiang@outlook.com

# Disqus site unique id
disqus: ioeworks

# Google analytics unique tracking id
google_analytics: UA-69801579-1

# Build settings
markdown: kramdown

# How many items to display on each page
paginate: 10
