# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: yuanjiang.space

# Site author
author: Yuan Jiang

# Website description
description: > # This means to ignore newlines until "baseurl:"
  Personal site for keeping notes, references, and bookmarks.

# The subpath of your site, e.g. /blog
baseurl: ""

# The base hostname & protocol for your site
url: "https://yuanjiang.space"
enforce_ssl: yuanjiang.space

# Twitter user id - leave it empty for privacy
twitter:

# Github user id
github: yuan-jiang

# LinkedIn user id - leave it empty for privacy
linkedin:

# Just give it any value or leave it empty
rss: true

# Contact email
email: W3l1YW5qaWFuZ0BvdXRsb29rLmNvbV0=

# Disqus site unique id
disqus: yuanjiangspace

# Google analytics unique tracking id
# google_analytics: UA-69801579-1

# Build settings
markdown: kramdown

# How many items to display on each page
paginate: 10

# Timezone info for posting blogs
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Tokyo

# Do not use the date in post url
# permalink: /:title.html
# Do not use the date and suffix in post url
permalink: /:title

# Plugin gems to enable below
plugins:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
